import { AudioLines, ChevronDown, Languages, Square, Volume2 } from 'lucide-react'
import type { AppModel } from '../hooks/useAppModel'
import type { AudioInput, Language } from '../services/types'
import { formatTime } from '../services/notes'

export function TranslatorPage({ model }: { model: AppModel }) {
  return <main className="page-scroll"><div className="page-wrap narrow animate-in"><div className="eyebrow">REAL-TIME INTERPRETER</div><h1>Phiên dịch trực tiếp</h1><p className="page-subtitle">Nhận diện tiếng Anh, tiếng Trung hoặc tiếng Việt từ microphone và âm thanh hệ thống.</p>
    <section className="glass-card translator-controls"><div className="select-row"><label className="field"><span>NGÔN NGỮ</span><div className="meeting-choice"><Languages size={17}/><select value={model.sourceLanguage} onChange={e => model.setSourceLanguage(e.target.value as Language)} disabled={model.capturing || model.busy}><option value="vi">Tiếng Việt</option><option value="en">Tiếng Anh → Tiếng Việt</option><option value="zh">Tiếng Trung → Tiếng Việt</option></select><ChevronDown size={17}/></div></label><label className="field"><span>ÂM THANH</span><div className="meeting-choice"><Volume2 size={17}/><select value={model.audioInput} onChange={e => model.setAudioInput(e.target.value as AudioInput)} disabled={model.capturing || model.busy}><option value="system">Âm thanh máy</option><option value="microphone">Micro</option><option value="both">Micro + âm thanh máy</option></select><ChevronDown size={17}/></div></label></div>
      {model.sourceLanguage !== 'vi' && <label className="toggle-row"><input type="checkbox" checked={model.speechEnabled} onChange={e => model.setSpeechEnabled(e.target.checked)}/><span>Đọc bản dịch bằng giọng Thức Dậy Đi</span></label>}
      <div className="action-row"><small>{model.status}</small><div className="row-spacer"/>{model.capturing ? <button className="pill-btn primary" onClick={() => void model.stop()}><Square size={14} fill="currentColor"/>Dừng</button> : <button className="pill-btn primary" onClick={() => void model.start()} disabled={!model.ready || model.busy}><AudioLines size={16}/>Bắt đầu</button>}</div></section>
    <section className="glass-card strong transcript-list"><h3>Bản ghi</h3>{model.entries.length ? model.entries.map(entry => { const block = model.translationBlocks.find(item => item.entryIds.at(-1) === entry.id); return <article key={entry.id} className="translation-entry"><small>{formatTime(entry.timestamp, false)}</small><p>{entry.sourceText}</p>{block && <div className={`translation-result ${block.pending ? 'pending' : ''}`}><small>TIẾNG VIỆT · DỊCH THEO ĐOẠN</small><p>{block.translatedText}</p></div>}</article> }) : <p className="muted">Chưa có lời nói được nhận diện.</p>}</section>
  </div></main>
}
